name: Closed fixed-pending-release issues
on:
    workflow_dispatch:
        inputs:
            message:
                description: "The message to be commented on issues that are closed due to being fixed."
                required: true

jobs:
    close_fixed_pending_release:
        runs-on: ubuntu-latest
        steps:
            - name: Close issues marked 'fixed-pending-release'
              uses: gcampbell-msft/fixed-pending-release@0.0.12
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                label: fixed-pending-release
                message: ${{ inputs.message }}
                isExternalRelease: true